### ISSUE TITLE
Which converter did you used to translate the COCO annotations to YOLOv5 annotations?

### ISSUE THREAD

**Issue by mikel-brostrom** [deepakcrk/yolov5-crowdhuman#10]
## ❔Question

I checked  `yolov5-crowdhuman/data/crowdhuman.yaml `

The original content of  the CrowdHuman dataset is `.odgt` for the annotations + `.jpg` for the images

Which tool did you use to convert the `.odgt` files to `.txt`?

**Comment by deepakcrk** [comment]
I wrote a small python script to convert data in .odgt to txt.

**Comment by mikel-brostrom** [comment]
Are you planning to upload this script to the repo?

**Comment by nomurakeiya** [comment]
@mikel-brostrom 
May be [this scripts](https://github.com/alaksana96/darknet-crowdhuman) will help you. (not yet test)

- crowdhuman_train_anno.py
- crowdhuman_val_anno.py

**Comment by mikel-brostrom** [comment]
Thx @nomurakeiya!
