### ISSUE TITLE
The full-body bounding box and the corresponding head box.

### ISSUE THREAD

**Issue by ReemAlharthi** [deepakcrk/yolov5-crowdhuman#2]
## ❔Question
Hello, 
Thank you so much for sharing the model weight. 
But, I have a question about the model prediction. The model's output appears to be a tensor of the bounding boxes and their corresponding class, which is either 1 for the head or 0 for the entire body. I would like to know if it's possible to find the corresponding head-box for each predicted full-body box. 
For example, if the image contains three people, the model output is a list of three full-body bounding boxes and three headboxes. I'm wondering if there's a way to link or associate each of the three full-body boxes to its head bounding box.

**Comment by deepakcrk** [comment]
Hi,
Currently, the class label 0 is for the body/person detection and 1 is for head.
You can find IOU the correspondence between head and body based on the overlap, on the top part of the body.

Current code is not doing that part.
