### ISSUE TITLE
How to show class name and class probability on the bounding box

### ISSUE THREAD

**Issue by thunanguyen** [deepakcrk/yolov5-crowdhuman#3]
## ❔Question
Hi, I want to ask how to use the detect code to show the class name (person, head) and probability like in the image in your repo. Because I've tried the code and it only gives the bounding box

**Comment by deepakcrk** [comment]
In https://github.com/deepakcrk/yolov5-crowdhuman/blob/master/utils/plots.py on line 64 you can modify for the same:
 `if label and False:` 
to
 `if label:`
