### ISSUE TITLE
Yolov5l/x trained on the crowd human dataset

### ISSUE THREAD

**Issue by mikel-brostrom** [deepakcrk/yolov5-crowdhuman#4]
## ❔Question

Hi! Thank you for the Yolov5m model trained on the crowd human dataset!
I use it in my object tracker [MOT16 evaluation](https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/wiki/Evaluation)
with very good results. I was wondering if you have plans of training a Yolov5l or even x model in a near future.

**Comment by deepakcrk** [comment]
@mikel-brostrom Thanks for the feedback.
Currently, I don't have any plan to train on yolov5(l)
